### ISSUE TITLE
Can't run GitSPDX.py from a directory other than its own.

### ISSUE THREAD

**Issue by ttgurney** [SPDX-Git/SPDX-Git-Scanner#43]
I tried running GitSPDX.py from a directory other than `src`:

```
$ cd ..
$ python ./src/GitSPDX.py branch=https://github.com/ttgurney/yocto-spdx.git
verbose        = True
tmpzip         = SPDXPackagedFiles.zip
spdxoutputbase = SPDXFile
printtype      = JSON
commitcomment  = SPDX Generation %Y%m%d%H%M%S
user           = 
branch         = https://github.com/ttgurney/yocto-spdx.git
password       = 
tmpdir         = ./TMP
database_pass  = 
database_port  = 
database_name  = 
database_host  = 
database_user  = 
Backing up DoSOCS settings file
******************************
Error during "Backing up DoSOCS settings file". Here's the exception that was raised:
Traceback (most recent call last):
  File "./src/GitSPDX.py", line 244, in <module>
    Main( commandLineConfig )
  File "./src/GitSPDX.py", line 229, in Main
    raise exc
IOError: [Errno 2] No such file or directory: './settings.py'
```

I also tried creating a symlink to `GitSPDX.py` in my home directory and running it from there. I received the same error.

It would be nice to have this tool "just work" regardless of what your current directory is when you invoke it.

**Comment by DanPatten** [comment]
This may take some major reworking to get this to work properly and at this time is a new feature outside of our use cases.
