### ISSUE TITLE
Permission denied when using tmpdir="/tmp"

### ISSUE THREAD

**Issue by ttgurney** [SPDX-Git/SPDX-Git-Scanner#46]
```
$ ./GitSPDX.py branch=https://github.com/ttgurney/yocto-spdx.git tmpdir="/tmp"
autocommit     = False
verbose        = True
tmpzip         = SPDXPackagedFiles.zip
spdxoutputbase = SPDXFile
printtype      = JSON
commitcomment  = SPDX Generation %Y%m%d%H%M%S
user           = 
branch         = https://github.com/ttgurney/yocto-spdx.git
password       = 
tmpdir         = /tmp
database_pass  = ....
database_name  = SPDX
FOSSOLOGY_PATH = /usr/share/fossology/nomos/agent/nomos
database_port  = 3306
database_host  = localhost
database_user  = spdx
Backing up DoSOCS settings file
Adding parameters to DoSOCS settings file
Deleting old temporary directory if present
******************************
Error during "Deleting old temporary directory if present". Here's the exception that was raised:
Traceback (most recent call last):
  File "./GitSPDX.py", line 250, in <module>
    Main( commandLineConfig )
  File "./GitSPDX.py", line 235, in Main
    raise exc
OSError: [Errno 13] Permission denied: '/tmp/tmpoCRGjC'
```

Each time I run the command it produces the error for the same directory: `/tmp/tmpoCRGjC`.
Running on spdxdev.ist.unomaha.edu.
/tmp has correct permissions (777).

**Comment by DanPatten** [comment]
Issue resolved due to /tmp directory needing delete and create perms.
