### ISSUE TITLE
DoSOCs Still Broken

### ISSUE THREAD

**Issue by Kazzira** [SPDX-Git/SPDX-Git-Scanner#9]
Traceback (most recent call last):
  File "TEST-SCRIPT.py", line 8, in <module>
    DoSPDX.dospdx(argHash)
  File "/media/sf_vbox/Test/DoSOCS/src/DoSPDX.py", line 141, in dospdx
    spdxDoc.generateSPDXDoc(scanOption)
  File "/media/sf_vbox/Test/DoSOCS/src/spdx.py", line 363, in generateSPDXDoc
    tempFileInfo.populateFileInfo(scanOption)
  File "/media/sf_vbox/Test/DoSOCS/src/fileInfo.py", line 478, in populateFileInfo
    self.getFileInfo(cached, dbCursor)
TypeError: getFileInfo() takes exactly 4 arguments (3 given)

Another instance where arguments were changed and breaks things.
Will fix soon.

**Comment by Kazzira** [comment]
fixed by removing package_id from the argument list of getFileInfo, since we do not need package_id to identify a row as package_file_id will do just fine.
